// <auto-generated />
using System;
using CalculadoraDebitos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculadora.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306120003_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Calculadora.Models.CalculoDebito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorCorrigidoUffi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorSelic")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalAtualizado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Calculos");
                });

            modelBuilder.Entity("Calculadora.Models.SelicMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualMensal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SelicMensal");
                });

            modelBuilder.Entity("Calculadora.Models.UffiAnual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UffiAnual");
                });
#pragma warning restore 612, 618
        }
    }
}
